version: '3'
services:
  node:
    build: backend/nodejs
    ports:
      - 3000:3000
  nginx:
    build: frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./search:/usr/share/nginx/html/search.json
    ports:
      - 80:80
